---

- name: Run show commands on routers
  hosts: cisco-routers
  gather_facts: false
  connection: local

  tasks:

    - include: tasks/ntc_show.yml ntc_command="sh ip int br"
    - include: tasks/ntc_show.yml ntc_command="sh ip route"
